sonar.sourceEncoding=UTF-8

sonar.sources=./src
sonar.tests=./test
sonar.exclusions=**/*.spec.ts
sonar.coverage.exclusions=/**/*.dto.ts,/**/*Dto.ts,/**/*.enum.ts,/**/*record.ts,/**/*Record.ts,/**/*module.ts,/**/constants/**,/**/tokens/**,/**/infrastructure/**,/**/*builder.ts,/**/*Builder.ts,/src/shared/errors/**,/**/main.ts,/**/index.ts,/**/log-response-body.interceptor.ts,/**/*.controller.ts,/**/currentUser.decorator.ts,/**/*.repository.ts,src/shared/user/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml
sonar.language=ts
