version: '3.7'

networks:
  net_dev:
    external: true

services:
  db:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - '5439:5432'
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  # films:
  #   image: aladiev/films
  #   restart: always
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - PG_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/postgres
  #   depends_on:
  #     - db
